language: csharp
mono: latest
dotnet: 2.1.4
dist: trusty
env: FrameworkPathOverride=/usr/lib/mono/4.5/
script:
 - dotnet restore
 - dotnet build -c Release
 - dotnet test -c Release --no-build Monacs.UnitTests/Monacs.UnitTests.fsproj
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd Monacs.Core && dotnet pack Monacs.Core.csproj -c Release -o . -v n && dotnet nuget push Monacs.Core.*.nupkg -k $NUGET_API_KEY -s https://www.nuget.org/api/v2/package
  on:
    branch: master
